---
version: "3"

vars:
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"

includes:
  flux:
    dir: .taskfiles/flux
    taskfile: .taskfiles/flux
  talos:
    taskfile: ".taskfiles/talos"
    dir: .taskfiles/talos

tasks:
  default:
    silent: true
    cmds:
      - task -l
