---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-storage
spec:
  interval: 30m
  chart:
    spec:
      chart: democratic-csi
      version: 0.14.6
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
      interval: 30m

  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace

  values:
    csiDriver:
      name: "org.democratic-csi.local-hostpath"
      attachRequired: false
      storageCapacity: true
      fsGroupPolicy: File

    storageClasses:
      - name: local-hostpath
        defaultClass: true
        reclaimPolicy: Delete
        volumeBindingMode: WaitForFirstConsumer
        allowVolumeExpansion: false
        parameters:

        mountOptions: []
        secrets:
          provisioner-secret:
          controller-publish-secret:
          node-stage-secret:
          node-publish-secret:
          controller-expand-secret:

    controller:
      enabled: true
      strategy: node
      externalProvisioner:
        extraArgs:
          - --leader-election=false
          - --node-deployment=true
          - --node-deployment-immediate-binding=false
          - --feature-gates=Topology=true
          - --strict-topology=true
          - --enable-capacity=true
          - --capacity-ownerref-level=1

      externalAttacher:
        enabled: false

      externalResizer:
        enabled: false

      externalSnapshotter:
        enabled: true
        extraArgs:
          - --leader-election=false
          - --node-deployment=true

    node:
      # https://github.com/democratic-csi/democratic-csi#a-note-on-non-standard-kubelet-paths
      kubeletHostPath: /var/snap/microk8s/common/var/lib/kubelet

      driver:
        extraVolumeMounts:
          - name: local-storage
            mountPath: /k8s-data
            mountPropagation: Bidirectional

      extraVolumes:
        - name: local-storage
          hostPath:
            path: /k8s-data
            type: DirectoryOrCreate

    driver:
      config:
        driver: local-hostpath
        instance_id:
        local-hostpath:
          shareBasePath: "/k8s-data"
          controllerBasePath: "/k8s-data"
          dirPermissionsMode: "0777"
          dirPermissionsUser: 0
          dirPermissionsGroup: 0
          snapshots:
            default_driver: filecopy
