---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
spec:
  interval: 30m
  chart:
    spec:
      chart: reloader
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: flux-system
      interval: 30m
  values:
    fullnameOverride: reloader
    reloader:
      readOnlyRootFileSystem: true
