---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudflared-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        credentials.json: |
          {
            "TunnelSecret": "{{ .cloudflare_tunnel_secret }}",
            "TunnelID": "{{ .cloudflare_tunnel_id }}"
          }
        TunnelID: "{{ .cloudflare_tunnel_id }}"
  data:
    - secretKey: cloudflare_tunnel_secret
      remoteRef:
        key: Cloudflare
        property: tunnel_secret
    - secretKey: cloudflare_tunnel_id
      remoteRef:
        key: Cloudflare
        property: tunnel_id

