---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "kreigan-com"
spec:
  secretName: "kreigan-com-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "kreigan.com"
  dnsNames:
    - "kreigan.com"
    - "*.kreigan.com"
