---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pg-superuser
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pg-superuser-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: PostgreSQL
        property: username
    - secretKey: password
      remoteRef:
        key: PostgreSQL
        property: password
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backblaze-pg-backup
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: backblaze-pg-backup-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        accessKeyId: "{{ .accessKeyId }}"
        secretAccessKey: "{{ .secretAccessKey }}"
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: accessKeyId
      remoteRef:
        key: Backblaze k8s-postgresql
        property: keyID
    - secretKey: secretAccessKey
      remoteRef:
        key: Backblaze k8s-postgresql
        property: applicationKey
