apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: cloudnative-pg-cluster-scheduled-backup
spec:
  schedule: "0 0 4 * * 0"
  backupOwnerReference: self
  cluster:
    name: cloudnative-pg-cluster
